title: AmFuture
email: info@fake.com
description: Our vision is to see spiritual and talented young minds with a bright future.
baseurl: ''
url: url
meta_author: Tom Hamilton Stubber

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
address:
  - Tirupati Mazima Mall
  - Level 2 Unit 251
  - Ggaba Rd, Nsambya
  - Kampala, Uganda
phone1: +256 706 559412
phone2: +256 783 011030
social:
  - title: facebook
    url: https://www.facebook.com/AmFuture-476703619089133/

socket_key: '6b04f212e12fd648efdc'

collections:
  posts:
    title: Blog
    output: true
    permalink: /blog/:title

defaults:
- scope:
    path: '_posts'
    type: posts
  values:
    layout: post
